name: Java CI with Maven

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Install dependencies and run tests
      run: mvn clean test -X

    - name: Generate Allure Report
      run: mvn allure:report

    - name: Publish Allure Report
      uses: actions/upload-artifact@v3  # Sử dụng v3 thay vì v2
      with:
        name: allure-report
        path: target/site/allure-maven
